# Generated by Django 6.0.3 on 2026-03-12 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EngineeringProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CR", "Cleanrooms"),
                            ("IOT", "IoT Solutions"),
                            ("FIRE", "Fire Systems"),
                            ("INT", "Interior Works"),
                        ],
                        max_length=4,
                    ),
                ),
                ("description", models.TextField()),
                ("main_image", models.ImageField(upload_to="projects/images/")),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="Link to project video (YouTube/Vimeo)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("service_interest", models.CharField(max_length=100)),
                (
                    "cad_drawing",
                    models.FileField(
                        upload_to="enquiries/drawings/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["dwg", "max", "pdf", "zip"]
                            )
                        ],
                    ),
                ),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
